# Generated by Django 5.1.7 on 2025-08-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="post_tag",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="tags.tag"
            ),
        ),
    ]
