# Generated by Django 5.2.1 on 2025-08-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='post_tag',
        ),
    ]
