# Generated by Django 5.2.1 on 2025-09-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_karma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='karma',
        ),
    ]
