# Generated by Django 5.2.1 on 2025-08-16 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(max_length=20)),
                ('context', models.CharField(blank=True, max_length=500, null=True)),
                ('community_tag', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('community_picture', models.ImageField(blank=True, null=True, upload_to='community/pics/')),
                ('community_banners', models.ImageField(blank=True, null=True, upload_to='community/banners/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
