# Generated by Django 5.2.1 on 2025-08-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='community_banners',
            new_name='community_banner',
        ),
    ]
