# Generated by Django 5.2.1 on 2025-08-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_rename_community_banners_community_community_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='community_tag',
        ),
    ]
