# Generated by Django 5.2.1 on 2025-08-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_community_community_tag'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='communities', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='community',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
