# Generated by Django 5.2.1 on 2025-08-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_community_tags_alter_community_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='tags',
            new_name='community_tags',
        ),
    ]
